apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: beltexam2
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: db-service
      port: 5432
      targetPort: 5432
