apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api-container
          image: 557701857917.dkr.ecr.ap-southeast-2.amazonaws.com/my-node-api-image
          env:
            - name: DB_HOST
              value: my-postgres-container
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: admin123
            - name: DB_NAME
              value: basic3tier
          ports:
            - containerPort: 3000
