apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api  # same label as the API pod (deploy-api.yml)
  ports:
    - protocol: TCP
      port: 81  # Port the API container is listening on
      targetPort: 3000  # Port the API container is using internally
