kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pv-claim  # Sets name of PVC
  namespace: beltexam2
  labels:
    app: db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size