kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pv-volume  # Sets PV's name
  namespace: beltexam2
  labels:
    type: local  # Sets PV's type to local
    app: db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"